# Generated by Django 2.2.1 on 2019-06-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='todoitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('due_date', models.DateTimeField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('list_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.todolist', to_field='name')),
            ],
        ),
    ]
