# Generated by Django 2.2.1 on 2019-06-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='list_name',
            new_name='todolist',
        ),
    ]
