# Generated by Django 2.2.2 on 2019-06-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
