# Generated by Django 2.2.2 on 2019-06-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplweb', '0002_auto_20190617_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='match_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matches',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
