# Generated by Django 2.2.2 on 2019-06-17 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iplweb', '0003_auto_20190617_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveries',
            name='match_id',
        ),
        migrations.AddField(
            model_name='deliveries',
            name='del_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iplweb.Matches', to_field='match_id'),
            preserve_default=False,
        ),
    ]
