import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'homeproject.settings')
django.setup()
from todoapp.models import todolist,todoitem

def add_data_todolist():
    insert = todolist(name = 'todolist1')
    insert.save()
    insert = todolist(name='todolist2')
    insert.save()
    insert = todolist(name='todolist3')
    insert.save()
    insert = todolist(name='todolist4')
    insert.save()
    insert = todolist(name='todolist5')
    insert.save()
    pass

def add_data_todoitem():
    insert = todoitem(description = 'list1item1',todolist_id = 'todolist1')
    insert.save()
    insert = todoitem(description='list1item2', todolist_id='todolist1')
    insert.save()
    insert = todoitem(description='list1item3', todolist_id='todolist1')
    insert.save()
    insert = todoitem(description='list1item4', todolist_id='todolist1')
    insert.save()
    insert = todoitem(description='list1item5', todolist_id='todolist1')
    insert.save()

    insert = todoitem(description='list2item1', todolist_id='todolist2')
    insert.save()
    insert = todoitem(description='list2item2', todolist_id='todolist2')
    insert.save()
    insert = todoitem(description='list2item3', todolist_id='todolist2')
    insert.save()
    insert = todoitem(description='list2item4', todolist_id='todolist2')
    insert.save()
    insert = todoitem(description='list2item5', todolist_id='todolist2')
    insert.save()

    insert = todoitem(description='list3item1', todolist_id='todolist3')
    insert.save()
    insert = todoitem(description='list3item2', todolist_id='todolist3')
    insert.save()
    insert = todoitem(description='list3item3', todolist_id='todolist3')
    insert.save()
    insert = todoitem(description='list3item4', todolist_id='todolist3')
    insert.save()
    insert = todoitem(description='list3item5', todolist_id='todolist3')
    insert.save()

    insert = todoitem(description='list4item1', todolist_id='todolist4')
    insert.save()
    insert = todoitem(description='list4item2', todolist_id='todolist4')
    insert.save()
    insert = todoitem(description='list4item3', todolist_id='todolist4')
    insert.save()
    insert = todoitem(description='list4item4', todolist_id='todolist4')
    insert.save()
    insert = todoitem(description='list4item5', todolist_id='todolist4')
    insert.save()

    insert = todoitem(description='list5item1', todolist_id='todolist5')
    insert.save()
    insert = todoitem(description='list5item2', todolist_id='todolist5')
    insert.save()
    insert = todoitem(description='list5item3', todolist_id='todolist5')
    insert.save()
    insert = todoitem(description='list5item4', todolist_id='todolist5')
    insert.save()
    insert = todoitem(description='list5item5', todolist_id='todolist5')
    insert.save()

#add_data_todolist()
add_data_todoitem()